%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 440.5 # 881.8372
Camera.fy: 442.3 # 884.7354
Camera.cx: 320.0 # 639.0745
Camera.cy: 180.0 # 359.0434

Camera.k1: 0.1303
Camera.k2: -0.3429
Camera.p1: 6.68e-4
Camera.p2: 5.149e-4
Camera.k3: 0.2390

# Camera resolution
Camera.width: 640 # 1280
Camera.height: 360 # 720

# Camera frames per second
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Transformation from body-frame (imu) to camera
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [0.999933, 0.0110568, -0.00328559, 0.0115119,
          -0.0109738, 0.999645, 0.0242987, -0.00288839,
          0.00355309, -0.024261, 0.999699, -0.00567426,
          0.0, 0.0, 0.0, 1.0]

# IMU noise
IMU.NoiseGyro: 2.0e-4
IMU.NoiseAcc: 3.5e-3
IMU.GyroWalk: 1.9393e-05
IMU.AccWalk: 3.0000e-03
IMU.Frequency: 200

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5 # -1.8
Viewer.ViewpointF: 500


