# Camera Model
Camera.name: "RealSense SR300"
Camera.setup: "RGBD" 
Camera.model: "perspective"

Camera.focal_x_baseline: 40

# Realsense SR300 Configurations
RS.filter_option: 7
RS.motion_range: 50

# ORB Parameters
Feature.max_num_keypoints: 1000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7

# PangolinViewer Parameters
PangolinViewer.keyframe_size: 0.05
PangolinViewer.keyframe_line_width: 1
PangolinViewer.graph_line_width: 1
PangolinViewer.point_size: 2
PangolinViewer.camera_size: 0.08
PangolinViewer.camera_line_width: 3
PangolinViewer.viewpoint_x: 0
PangolinViewer.viewpoint_y: -0.9
PangolinViewer.viewpoint_z: -1.9
PangolinViewer.viewpoint_f: 400

